# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/_DATN/FFT/FFT_final/FFT_final.srcs/sources_1/bd/DDS_FFT_ethernet_final/ip/DDS_FFT_ethernet_final_processing_system7_0_0/DDS_FFT_ethernet_final_processing_system7_0_0.xci
# IP: The module: 'DDS_FFT_ethernet_final_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/_DATN/FFT/FFT_final/FFT_final.gen/sources_1/bd/DDS_FFT_ethernet_final/ip/DDS_FFT_ethernet_final_processing_system7_0_0/DDS_FFT_ethernet_final_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_FFT_ethernet_final_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Vivado/_DATN/FFT/FFT_final/FFT_final.srcs/sources_1/bd/DDS_FFT_ethernet_final/ip/DDS_FFT_ethernet_final_processing_system7_0_0/DDS_FFT_ethernet_final_processing_system7_0_0.xci
# IP: The module: 'DDS_FFT_ethernet_final_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/_DATN/FFT/FFT_final/FFT_final.gen/sources_1/bd/DDS_FFT_ethernet_final/ip/DDS_FFT_ethernet_final_processing_system7_0_0/DDS_FFT_ethernet_final_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_FFT_ethernet_final_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
