# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/bd/FFT_update/ip/FFT_update_processing_system7_0_0/FFT_update_processing_system7_0_0.xci
# IP: The module: 'FFT_update_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.gen/sources_1/bd/FFT_update/ip/FFT_update_processing_system7_0_0/FFT_update_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_update_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/bd/FFT_update/ip/FFT_update_processing_system7_0_0/FFT_update_processing_system7_0_0.xci
# IP: The module: 'FFT_update_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.gen/sources_1/bd/FFT_update/ip/FFT_update_processing_system7_0_0/FFT_update_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_update_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
