# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/bd/FFT_update/ip/FFT_update_DDS_FFT_0_2/FFT_update_DDS_FFT_0_2.xci
# IP: The module: 'FFT_update_DDS_FFT_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/ip/xfft_0/xfft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/ip/dds_compiler_2/dds_compiler_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_2 || ORIG_REF_NAME==dds_compiler_2} -quiet] -quiet

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_1 || ORIG_REF_NAME==dds_compiler_1} -quiet] -quiet

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# XDC: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.gen/sources_1/bd/FFT_update/ip/FFT_update_DDS_FFT_0_2/FFT_update_DDS_FFT_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_update_DDS_FFT_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/bd/FFT_update/ip/FFT_update_DDS_FFT_0_2/FFT_update_DDS_FFT_0_2.xci
# IP: The module: 'FFT_update_DDS_FFT_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/ip/xfft_0/xfft_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/ip/dds_compiler_2/dds_compiler_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_2 || ORIG_REF_NAME==dds_compiler_2} -quiet] -quiet

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_1 || ORIG_REF_NAME==dds_compiler_1} -quiet] -quiet

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# XDC: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.gen/sources_1/bd/FFT_update/ip/FFT_update_DDS_FFT_0_2/FFT_update_DDS_FFT_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_update_DDS_FFT_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
