# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DDS_FFT_ethernet_final/DDS_FFT_ethernet_final.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_FFT_ethernet_final || ORIG_REF_NAME==DDS_FFT_ethernet_final} -quiet] -quiet

# IP: bd/DDS_FFT_ethernet_final/ip/DDS_FFT_ethernet_final_processing_system7_0_0/DDS_FFT_ethernet_final_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_FFT_ethernet_final_processing_system7_0_0 || ORIG_REF_NAME==DDS_FFT_ethernet_final_processing_system7_0_0} -quiet] -quiet

# IP: bd/DDS_FFT_ethernet_final/ip/DDS_FFT_ethernet_final_ila_0_0/DDS_FFT_ethernet_final_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_FFT_ethernet_final_ila_0_0 || ORIG_REF_NAME==DDS_FFT_ethernet_final_ila_0_0} -quiet] -quiet

# IP: bd/DDS_FFT_ethernet_final/ip/DDS_FFT_ethernet_final_ps7_0_axi_periph_0/DDS_FFT_ethernet_final_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_FFT_ethernet_final_ps7_0_axi_periph_0 || ORIG_REF_NAME==DDS_FFT_ethernet_final_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DDS_FFT_ethernet_final/ip/DDS_FFT_ethernet_final_rst_ps7_0_100M_0/DDS_FFT_ethernet_final_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_FFT_ethernet_final_rst_ps7_0_100M_0 || ORIG_REF_NAME==DDS_FFT_ethernet_final_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/DDS_FFT_ethernet_final/ip/DDS_FFT_ethernet_final_myFFT_0_2/DDS_FFT_ethernet_final_myFFT_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_FFT_ethernet_final_myFFT_0_2 || ORIG_REF_NAME==DDS_FFT_ethernet_final_myFFT_0_2} -quiet] -quiet

# IP: bd/DDS_FFT_ethernet_final/ip/DDS_FFT_ethernet_final_DDS_FFT_0_0/DDS_FFT_ethernet_final_DDS_FFT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_FFT_ethernet_final_DDS_FFT_0_0 || ORIG_REF_NAME==DDS_FFT_ethernet_final_DDS_FFT_0_0} -quiet] -quiet

# IP: ip/xfft_0/xfft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# IP: ip/dds_compiler_2/dds_compiler_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_2 || ORIG_REF_NAME==dds_compiler_2} -quiet] -quiet

# IP: ip/dds_compiler_1/dds_compiler_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_1 || ORIG_REF_NAME==dds_compiler_1} -quiet] -quiet

# IP: ip/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: bd/DDS_FFT_ethernet_final/ip/DDS_FFT_ethernet_final_auto_pc_0/DDS_FFT_ethernet_final_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_FFT_ethernet_final_auto_pc_0 || ORIG_REF_NAME==DDS_FFT_ethernet_final_auto_pc_0} -quiet] -quiet

# XDC: d:/Vivado/_DATN/FFT/FFT_final/FFT_final.gen/sources_1/bd/DDS_FFT_ethernet_final/DDS_FFT_ethernet_final_ooc.xdc
