# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/ip/dds_compiler_2/dds_compiler_2.xci
# IP: The module: 'dds_compiler_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.gen/sources_1/ip/dds_compiler_2/dds_compiler_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.srcs/sources_1/ip/dds_compiler_2/dds_compiler_2.xci
# IP: The module: 'dds_compiler_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.gen/sources_1/ip/dds_compiler_2/dds_compiler_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
