# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/FFT_update/FFT_update.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFT_update || ORIG_REF_NAME==FFT_update} -quiet] -quiet

# IP: bd/FFT_update/ip/FFT_update_processing_system7_0_0/FFT_update_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFT_update_processing_system7_0_0 || ORIG_REF_NAME==FFT_update_processing_system7_0_0} -quiet] -quiet

# IP: bd/FFT_update/ip/FFT_update_ila_0_0/FFT_update_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFT_update_ila_0_0 || ORIG_REF_NAME==FFT_update_ila_0_0} -quiet] -quiet

# IP: bd/FFT_update/ip/FFT_update_ps7_0_axi_periph_0/FFT_update_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFT_update_ps7_0_axi_periph_0 || ORIG_REF_NAME==FFT_update_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/FFT_update/ip/FFT_update_rst_ps7_0_100M_0/FFT_update_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFT_update_rst_ps7_0_100M_0 || ORIG_REF_NAME==FFT_update_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/FFT_update/ip/FFT_update_DDS_FFT_0_2/FFT_update_DDS_FFT_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFT_update_DDS_FFT_0_2 || ORIG_REF_NAME==FFT_update_DDS_FFT_0_2} -quiet] -quiet

# IP: ip/xfft_0/xfft_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xfft_0 || ORIG_REF_NAME==xfft_0} -quiet] -quiet

# IP: ip/dds_compiler_2/dds_compiler_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_2 || ORIG_REF_NAME==dds_compiler_2} -quiet] -quiet

# IP: ip/dds_compiler_1/dds_compiler_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_1 || ORIG_REF_NAME==dds_compiler_1} -quiet] -quiet

# IP: ip/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: bd/FFT_update/ip/FFT_update_myFFT_0_1/FFT_update_myFFT_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFT_update_myFFT_0_1 || ORIG_REF_NAME==FFT_update_myFFT_0_1} -quiet] -quiet

# IP: bd/FFT_update/ip/FFT_update_auto_pc_0/FFT_update_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FFT_update_auto_pc_0 || ORIG_REF_NAME==FFT_update_auto_pc_0} -quiet] -quiet

# XDC: d:/Vivado/_DATN/FFT/FFT_update/FFT_update.gen/sources_1/bd/FFT_update/FFT_update_ooc.xdc
